##
##    Cassandra opscenter kubernetes version
##
##
FROM debian:wheezy
MAINTAINER Mikel Nelson <mikel.n@samsung.com>

# Add PPA for the necessary JDK
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886 \
    &&  DEBIAN_FRONTEND=noninteractive apt-get update -y \
    &&  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    sudo \
    &&  echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/datastax.sources.list \
    &&  curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add - \
    &&  DEBIAN_FRONTEND=noninteractive apt-get update -y \
    &&  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    opscenter=5.1.1 \
    && DEBIAN_FRONTEND=noninteractive apt-get autoremove -y \
    &&  DEBIAN_FRONTEND=noninteractive apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Deploy startup script
COPY init.sh /usr/local/bin/ops-dock
COPY shutdown.sh /usr/local/bin/ops-stop
RUN chmod 755 /usr/local/bin/ops-dock \
    &&  chmod 755 /usr/local/bin/ops-stop

# opscenter ports
EXPOSE 8888 50031 61620
# agent ports...(just to be safe)
#EXPOSE 7199 8012 61621 22 
EXPOSE 7199 8012 61621 
# cassandra ports...(just to be safe)
EXPOSE 7000 7001 9160 9042
USER root
CMD ops-dock
